name: Build, Deploy, or Promote to Sandbox

on:
  workflow_call:
    inputs:
      build-deploy-promote: 
        description: Specify whether you would like to build the jar file or build and deploy or promote a tag
        required: false
        type: string
        default: 'build'
      code-coverage-required:
        description: Specify whether code coverage is required for maven to succeed
        required: false
        type: boolean
        default: true
      muleEnv:
        description: Mule environment to deploy to
        required: false
        type: string
        default: 'Development'
      artifactGroup:
        description: Specify Group ID for artifact
        required: false
        type: string
        default: ''
      tag:
        description: Specify tag to promote
        required: false
        type: string
        default: ''


jobs:
  Checkout-Repo:
    if: ${{ inputs.build-deploy-promote == 'build' || inputs.build-deploy-promote == 'deploy' }}
    runs-on: self-hosted
    steps:
    - name: Checkout this repo
      if: ${{ inputs.tag == '' }}
      uses: actions/checkout@v4
    - name: Checkout specific tag
      if: ${{ inputs.tag != '' }}
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.tag }}
 #   - name: Cache dependencies
 #     uses: actions/cache@v3
 #     with:
 #       path: ~/.m2/repository
 #       key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
 #       restore-keys: |
 #         ${{ runner.os }}-maven-
    - name: Checkout settings.xml
      uses: actions/checkout@v4
      with: 
        repository: "eldeekhowong/shared-workflows"
        path: "shared-workflows"
        sparse-checkout: "maven/eits_mulesoft_settings.xml"
    

  Build-Package:
    if: ${{ inputs.build-deploy-promote == 'build'}}
    needs: Checkout-Repo
    runs-on: self-hosted
    steps:
    - name: Build with Maven
      run: mvn -B -s shared-workflows/maven/eits_mulesoft_settings.xml clean package -DcodeCoverageRequired=${{inputs.code-coverage-required}} --file pom.xml


  Deploy-Package-Artifactory:
    if: ${{ inputs.build-deploy-promote == 'deploy' }}
    needs: Checkout-Repo
    runs-on: self-hosted
    steps:
    - name: Deploy package to Artifactory
      run: mvn -B -s shared-workflows/maven/eits_mulesoft_settings.xml clean deploy -DskipTests -DcodeCoverageRequired=${{inputs.code-coverage-required}} --file pom.xml


  Tag-Artifact:
    if: ${{ inputs.build-deploy-promote == 'deploy' }}
    needs: Deploy-Package-Artifactory
    runs-on: self-hosted
    steps:
    - name: Extract artifact version
      id: extract-artifact-version
      run: |
        ARTIFACT_VERSION=$(ls target/*.jar | head -1 | awk '{print substr($1,length($1)-50,21)}')
        echo "ARTIFACT_VERSION=$ARTIFACT_VERSION" >> "$GITHUB_OUTPUT"
    - name: Tag with artifact version
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: 'refs/tags/${{ steps.extract-artifact-version.outputs.ARTIFACT_VERSION }}',
            sha: context.sha
          })


  Download-Package-Artifactory:
    if: ${{ inputs.build-deploy-promote == 'promote' }}
    runs-on: self-hosted
    steps:
    - name: Download package
      run: |
        echo "HELLO"

    
  Deploy-Package-Anypoint:
    if: ${{ inputs.build-deploy-promote == 'deploy' }}
    needs: [Tag-Artifact]
    runs-on: self-hosted
    steps:
    - name: Deploy to Anypoint Platform
      uses: eldeekhowong/shared-workflows/.github/workflows/eits-anypoint-deploy.yml@main


  Promote-Package-Anypoint:
    if: ${{ inputs.build-deploy-promote == 'promote' }}
    needs: [Download-Package-Artifactory]
    runs-on: self-hosted
    steps:
    - name: Deploy to Anypoint Platform
      uses: eldeekhowong/shared-workflows/.github/workflows/eits-anypoint-deploy.yml@main