name: Build, Deploy, or Promote to Sandbox

on:
  workflow_call:
    inputs:
      build-deploy-promote: 
        description: Specify whether you would like to build the jar file or build and deploy or promote a tag
        required: false
        type: string
        default: 'build'
      code-coverage-required:
        description: Specify whether code coverage is required for maven to succeed
        required: false
        type: boolean
        default: true
      muleEnv:
        description: Mule environment to deploy to
        required: false
        type: string
        default: 'Development'
#      artifactGroup:
#        description: Specify Group ID for artifact
#        required: false
#        type: string
#        default: ''
      tag:
        description: Specify tag to promote
        required: false
        type: string
        default: ''


jobs:
  Checkout-Repo:
    runs-on: self-hosted
    steps:
    - name: Checkout this repo
      if: ${{ inputs.tag == '' }}
      uses: actions/checkout@v4
    - name: Checkout specific tag
      if: ${{ inputs.tag != '' }}
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.tag }}
 #   - name: Cache dependencies
 #     uses: actions/cache@v3
 #     with:
 #       path: ~/.m2/repository
 #       key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
 #       restore-keys: |
 #         ${{ runner.os }}-maven-
    - name: Checkout settings.xml
      uses: actions/checkout@v4
      with: 
        repository: "eldeekhowong/shared-workflows"
        path: "shared-workflows"
        sparse-checkout: "maven/eits_mulesoft_settings.xml"
    

  Build-Package:
    needs: Checkout-Repo
    runs-on: self-hosted
    steps:
    - name: Build with Maven
      run: mvn -B -s shared-workflows/maven/eits_mulesoft_settings.xml package -DcodeCoverageRequired=${{inputs.code-coverage-required}} --file pom.xml


  Deploy-Package:
    if: ${{ inputs.build-deploy-promote == 'deploy' }}
    needs: Build-Package
    runs-on: self-hosted
    steps:
    - name: Deploy package to Artifactory
      run: mvn -s shared-workflows/maven/eits_mulesoft_settings.xml -B deploy -DcodeCoverageRequired=${{inputs.code-coverage-required}} --file pom.xml

    - name: Deploy to Runtime Manager
      env:
        CLIENT_ID: ${{ secrets.anypoint_platform_client_id }}
        CLIENT_SECRET: ${{ secrets.anypoint_platform_client_secret }}
      run: |
        artifactName=$(ls target/*.jar | head -1)
        mvn -B -s shared-workflows/maven/eits_mulesoft_settings.xml deploy -DmuleDeploy -Danypoint.client_id="$CLIENT_ID" -Danypoint.client_secret="$CLIENT_SECRET" -Dmule.artifact=$artifactName -Danypoint.muleEnv="$ANYPOINT_ENV"

    - name: Retrieve artifact version
      id: retrieve-artifact-version
      run: |
        ARTIFACT_VERSION=$(ls target/*.jar | head -1 | awk '{print substr($1,length($1)-50,21)}')
        echo "ARTIFACT_VERSION=$ARTIFACT_VERSION" >> "$GITHUB_OUTPUT"

    - name: Tag with artifact version
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: 'refs/tags/${{ steps.retrieve-artifact-version.outputs.ARTIFACT_VERSION }}',
            sha: context.sha
          })


  Promote-Build:
    if: ${{ inputs.build-deploy-promote == 'promote' }}
    needs: Build-Package
    runs-on: self-hosted
    steps:
    - name: Deploy to Runtime Manager
      env:
        CLIENT_ID: ${{ secrets.anypoint_platform_client_id }}
        CLIENT_SECRET: ${{ secrets.anypoint_platform_client_secret }}
        ANYPOINT_ENV: ${{ inputs.muleEnv }}
      run: |
        artifactName=$(ls target/*.jar | head -1)
        mvn -B -s shared-workflows/maven/eits_mulesoft_settings.xml deploy -DmuleDeploy -Danypoint.client_id="$CLIENT_ID" -Danypoint.client_secret="$CLIENT_SECRET" -Dmule.artifact=$artifactName -Danypoint.muleEnv="$ANYPOINT_ENV"