name: EITS Promote Artifact Job

on:
  workflow_call:
    inputs:
      muleEnv:
        description: Mule environment to deploy to
        required: false
        type: string
        default: 'Development'
      artifactGroup:
        description: Specify Group ID for artifact
        required: false
        type: string
        default: ''
      tag:
        description: Specify tag to promote
        required: false
        type: string
        default: ''
      branch:
        description: Specify branch to checkout
        required: false
        type: string
        default: ''

jobs:
  Checkout-Repo:
    runs-on: self-hosted
    steps:
    - name: Checkout this repo
      if: ${{ inputs.branch == '' }}
      uses: actions/checkout@v4
    - name: Checkout specific branch
      if: ${{ inputs.branch != '' }}
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.branch }}
    - name: Checkout EITS configuration settings
      uses: actions/checkout@v4
      with: 
        repository: "eldeekhowong/shared-workflows"
        path: "shared-workflows"
        sparse-checkout: |
          maven
          configuration
    

  Download-Artifact-Artifactory:
    needs: [Checkout-Repo]
    runs-on: self-hosted
    steps:
    - name: Download artifact
      id: download-artifact
      run: |
        artifactName=${{ inputs.artifactGroup }}:${{ github.event.repository.name }}:${{ inputs.tag }}:jar:mule-application
        echo Downloading $artifactName
        ${{vars.MVN_COMMAND}} dependency:copy -Dartifact=$artifactName -DoutputDirectory=target/. -Dtransitive=false

        ARTIFACT_MAJOR_VERSION=$(echo ${{ inputs.tag }} | cut -d '-' -f 1 | cut -d '.' -f 1)
        echo "Artifact Major Version: $ARTIFACT_MAJOR_VERSION"
        echo "ARTIFACT_MAJOR_VERSION=$ARTIFACT_MAJOR_VERSION" >> "$GITHUB_OUTPUT"
    outputs:
      ARTIFACT_MAJOR_VERSION: ${{ steps.download-artifact.outputs.ARTIFACT_MAJOR_VERSION }}


  Promote-Artifact-Anypoint:
    needs: [Download-Artifact-Artifactory]
    uses: eldeekhowong/shared-workflows/.github/workflows/eits-anypoint-deploy.yaml@main
    secrets: inherit
    with:
      muleEnv: ${{ inputs.muleEnv }}
      majorVersion: ${{ needs.Download-Artifact-Artifactory.outputs.ARTIFACT_MAJOR_VERSION }}