name: EITS Increment Version

on:
  workflow_call:
    inputs:
      version:
        description: Increment Version
        required: true
        type: string
      branch:
        description: Branch to create PR from
        required: true
        type: string


jobs:
  Increment-Version:
    runs-on: self-hosted
    steps:
    - name: Checkout target branch
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.branch }}

    - name: Checkout settings.xml
      uses: actions/checkout@v4
      with: 
        repository: "eldeekhowong/shared-workflows"
        path: "shared-workflows"
        sparse-checkout: "maven"

    - name: Configure Git
      run: |
        git config --global user.email "gabot@eldee.com"
        git config --global user.name "Git Action Bot"
    
    - name: Create increment version branch
      run: |
        git checkout -b increment-${{ inputs.version }}
    
    - name: Update pom.xml with new version
      run: |
        echo "New version: ${{ inputs.version }}"
        ${{ vars.MVN_COMMAND }} versions:set -DnewVersion="${{ inputs.version }}"
  
    - name: Commit and push changes
      run: |
        git add "pom.xml"
        git commit -m "Incremented POM version to ${{ inputs.version }}"
        git push -f -u origin HEAD
    
    - name: Pull Request from increment version branch to target branch
      uses: actions/github-script@v7
      with:
        script: |
          const { repo, owner } = context.repo;
          const result = await github.rest.pulls.create({
            title: 'Automated PR to update POM version to ${{ inputs.version }}',
            owner,
            repo,
            head: 'increment-${{ inputs.version }}',
            base: ${{ inputs.branch }},
            body: [
              'This PR is auto-generated by',
              '[actions/github-script](https://github.com/actions/github-script).'
            ].join('\n')
          });
          await github.rest.pulls.merge({
            owner: owner,
            repo: repo,
            pull_number: result.data.number
          });

    - name: Delete increment version branch
      run: |
        git push origin --delete increment-${{ inputs.version }}