name: EITS Increment Version

on:
  workflow_call:
    inputs:
      version:
        description: Incremented Version (without -SNAPSHOT)
        required: true
        type: string


jobs:
  Update-Version:
    runs-on: self-hosted
    steps:
    - name: Checkout this repo
      uses: actions/checkout@v4
      with:
        ref: "develop"

    - name: Configure Git
      run: |
        git config --global user.email "gabot@eldee.com"
        git config --global user.name "Git Action Bot"
    
    - name: Switch to branch
      run: |
        git checkout -b ${{ inputs.version }}
    
    - name: Set new version
      run: |
        echo ${{ inputs.version }} 
        echo "HELLO" >> mule-artifact.json
  
    - name: Commit and push
      run: |
        git add "mule-artifact.json"
        git commit -m "Incrementing POM version to ${{ inputs.version }}"
        git push -f -u origin HEAD
    
    - name: Create Pull Request
      uses: actions/github-script@v7
      with:
        script: |
          const { repo, owner } = context.repo;
          const result = await github.rest.pulls.create({
            title: 'Automated PR to update POM version to ${{ inputs.version }}',
            owner,
            repo,
            head: '${{ inputs.version }}',
            base: 'develop',
            body: [
              'This PR is auto-generated by',
              '[actions/github-script](https://github.com/actions/github-script).'
            ].join('\n')
          });
          console.log(result.data.number);
          const result2 = await github.rest.pulls.merge({
            owner: owner,
            repo: repo,
            pull_number: result.data.number
          });
          console.log(result2);


#  Increment-Version:
 #   needs: Checkout-Repo
 #   runs-on: self-hosted
 #   steps:
 #   - name: Set new version
 #     run: |
 #       echo ${input.version}
 #       run: ${{vars.MVN_COMMAND}} versions:set -DnewVersion="${input.version}-\${maven.build.timestamp}-SNAPSHOT"




#  Commit-Changes:
#    runs-on: self-hosted
#    steps:
#    - name: Checkout this repo
#      uses: actions/checkout@v4
#    - name: Checkout settings.xml
#      uses: actions/checkout@v4
#      with: 
#        repository: "eldeekhowong/shared-workflows"
#        path: "shared-workflows"
#        sparse-checkout: "maven"