name: EITS Anypoint Deploy

on:
  workflow_call:
    inputs:
      muleEnv:
        description: Mule environment to deploy to
        required: false
        type: string
        default: 'Development'
      majorVersion:
        description: API major version
        required: true
        type: string

jobs:
  Anypoint-Deploy-Configuration:
    runs-on: self-hosted
    steps:  
    - name: Read Anypoint Deploy Configuration
      id: read-anypoint-deploy-configuration
      run: |
        matrix=$(cat ./shared-workflows/configuration/Development/anypoint-deploy-configuration.json)
        ### Remove JSON line breaks ###
        matrix="${matrix//$'\n'/''}"
        ### Remove JSON line breaks ###
        echo "anypoint-deploy-configuration.json: $matrix"
        echo "repositoryName: ${{github.event.repository.name}}"
        echo "matrix=$matrix" >> $GITHUB_OUTPUT
    outputs:
      matrix: ${{ steps.read-anypoint-deploy-configuration.outputs.matrix }}

  Anypoint-Deploy:
    needs: Anypoint-Deploy-Configuration
    runs-on: self-hosted
    strategy:
      matrix: ${{ fromJSON(needs.Anypoint-Deploy-Configuration.outputs.matrix) }}
    steps:
    - name: Deploy to Anypoint Platform
      if: ${{ matrix.repositoryName == github.event.repository.name }}
      env:
        CLIENT_ID: ${{ secrets.anypoint_platform_client_id }}
        CLIENT_SECRET: ${{ secrets.anypoint_platform_client_secret }}
        GRANT_TYPE: ${{ secrets.anypoint_platform_grant_type }}
        REPOSITORY_NAME: ${{ matrix.repositoryName }}
        MULE_MAVEN_PLUGIN_VERSION: ${{ matrix.muleMavenPluginVersion }}
        CH_URI: ${{ matrix.uri }}
        CH_MULE_VERSION: ${{ matrix.muleVersion }}
        CH_BUSINESS_GROUP: ${{ matrix.businessGroup }}
        CH_APPLICATION_NAME: ${{ matrix.applicationName }}
        CH_ENVIRONMENT: ${{ inputs.muleEnv }}
        CH_REGION: ${{ matrix.region }}
        CH_WORKERS: ${{ matrix.workers }}
        CH_WORKER_TYPE: ${{ matrix.workerType }}
        CH_OBJECT_STORE_V2: ${{ matrix.objectStoreV2 }}
      run: |
        artifactName=$(ls target/*.jar | head -1)
        echo $artifactName
        echo "Repository Name: $REPOSITORY_NAME"
        ch_application_name=$CH_APPLICATION_NAME
        ch_application_name_version=${ch_application_name/\{version\}/v1}
        echo "CH Application Name Version: $ch_application_name_version"
        ${{vars.MVN_COMMAND}} mule:deploy -Danypoint.client_id="$CLIENT_ID" -Danypoint.client_secret="$CLIENT_SECRET" -Danypoint.grant_type="$GRANT_TYPE" -Dmule.artifact=$artifactName -Dmule.maven.plugin.version="$MULE_MAVEN_PLUGIN_VERSION" -Dch.uri="$CH_URI" -Dch.muleVersion="$CH_MULE_VERSION" -Dch.businessGroup="$CH_BUSINESS_GROUP" -Dch.applicationName="$ch_application_name_version" -Dch.environment="$CH_ENVIRONMENT" -Dch.region="$CH_REGION" -Dch.workers="$CH_WORKERS" -Dch.workerType="$CH_WORKER_TYPE" -Dch.objectStoreV2="$CH_OBJECT_STORE_V2"