name: EITS Anypoint Deploy

on:
  workflow_call:
    inputs:
      muleEnv:
        description: Mule environment to deploy to
        required: false
        type: string
        default: 'Development'


jobs:
  Anypoint-Deploy:
    runs-on: self-hosted
    steps:
    - name: Deploy to Anypoint Platform
      env:
        CLIENT_ID: ${{ secrets.anypoint_platform_client_id }}
        CLIENT_SECRET: ${{ secrets.anypoint_platform_client_secret }}
        ANYPOINT_ENV: ${{ inputs.muleEnv }}
      run: |
        artifactName=$(ls target/*.jar | head -1)
        echo $artifactName
        ${{vars.MVN_COMMAND}} deploy -DskipTests -DmuleDeploy -Danypoint.client_id="$CLIENT_ID" -Danypoint.client_secret="$CLIENT_SECRET" -Dmule.artifact=$artifactName -Danypoint.muleEnv="$ANYPOINT_ENV"