name: EITS Update Version Job

on:
  workflow_call:
    inputs:
      version:
        description: New version
        required: false
        type: string
      branch:
        description: Branch to update
        required: true
        type: string
      calculate-release:
        description: Automatically calculate release version
        required: false
        type: boolean
        default: false


jobs:
  Set-New-Version:
    runs-on: self-hosted
    env:
      VERSION: ${{ inputs.version }}
    steps:
    - name: Checkout target branch
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.branch }}

    - name: Checkout settings.xml
      uses: actions/checkout@v4
      with: 
        repository: "eldeekhowong/shared-workflows"
        path: "shared-workflows"
        sparse-checkout: "maven"

    - name: Calculate release version
      if: ${{ inputs.calculate-release == true }}
      run: |
        CURRENT_VERSION=$(${{ vars.MVN_COMMAND }} help:evaluate -Dexpression=project.version -q -DforceStdout)
        echo "Current Version: $CURRENT_VERSION"
        RELEASE_VERSION=$(echo $CURRENT_VERSION | cut -d '-' -f 1)
        echo "Release Version: $RELEASE_VERSION"
        echo "VERSION=$RELEASE_VERSION" >> $GITHUB_ENV

    - name: Configure Git
      run: |
        git config --global user.email "gabot@eldee.com"
        git config --global user.name "Git Action Bot"
    
    - name: Create new version branch
      run: |
        git checkout -b new-version-${{ env.VERSION }}
    
    - name: Update pom.xml with new version
      run: |
        echo "New version: ${{ env.VERSION }}"
        ${{ vars.MVN_COMMAND }} versions:set -DnewVersion="${{ env.VERSION }}"
  
    - name: Commit and push changes
      run: |
        git add "pom.xml"
        git commit -m "Updated POM version to ${{ env.VERSION }}"
        git push -f -u origin HEAD
    
    - name: Pull Request from new version branch to target branch
      uses: actions/github-script@v7
      with:
        script: |
          const { repo, owner } = context.repo;
          const result = await github.rest.pulls.create({
            title: 'Automated PR to update POM version to ${{ env.VERSION }}',
            owner,
            repo,
            head: 'new-version-${{ env.VERSION }}',
            base: '${{ inputs.branch }}',
            body: [
              'This PR is auto-generated by',
              '[actions/github-script](https://github.com/actions/github-script).'
            ].join('\n')
          });
          await github.rest.pulls.merge({
            owner: owner,
            repo: repo,
            pull_number: result.data.number
          });

    - name: Delete new version branch
      run: |
        git push origin --delete new-version-${{ env.VERSION }}