name: EITS Anypoint Deploy

on:
  workflow_call:
    inputs:
      muleEnv:
        description: Mule environment to deploy to
        required: false
        type: string
        default: 'Development'


jobs:
  Anypoint-Deploy-Configuration:
    runs-on: self-hosted
    steps:  
    - name: Read Anypoint Deploy Configuration
      id: read-anypoint-deploy-configuration
      run: |
        matrix=$(cat ./shared-workflows/configuration/Development/anypoint-deploy-configuration.json)
        echo "anypoint-deploy-configuration.json: $matrix"
        echo "repositoryName: ${{github.event.repository.name}}"
        echo "matrix=$matrix" >> $GITHUB_OUTPUT
    outputs:
      matrix: ${{ steps.read-anypoint-deploy-configuration.outputs.matrix }}

  Anypoint-Deploy:
    needs: Anypoint-Deploy-Configuration
    runs-on: self-hosted
    strategy:
      matrix: ${{ fromJSON(needs.Anypoint-Deploy-Configuration.outputs.matrix) }}
    steps:
    - name: Deploy to Anypoint Platform
      env:
        CLIENT_ID: ${{ secrets.anypoint_platform_client_id }}
        CLIENT_SECRET: ${{ secrets.anypoint_platform_client_secret }}
        ANYPOINT_ENV: ${{ inputs.muleEnv }}
      run: |
        artifactName=$(ls target/*.jar | head -1)
        echo $artifactName
        echo ${{ matrix.repositoryName }}
        echo ${{ matrix.workers}}
        # ${{vars.MVN_COMMAND}} mule:deploy -Danypoint.client_id="$CLIENT_ID" -Danypoint.client_secret="$CLIENT_SECRET" -Dmule.artifact=$artifactName -Danypoint.muleEnv="$ANYPOINT_ENV"