name: Main Configuration file for orchestration of pipeline

on:
  workflow_call:

jobs:
  Run-Tests:
    if: ${{ GITHUB.event_name != 'pull_request' }}
    uses: eldeekhowong/shared-workflows/.github/workflows/build-test.yml@main
    secrets: inherit