name: EITS Main Mule Pipeline

on:
  workflow_call:

jobs:
  Feature-Branch-Commit:
    if: ${{ startsWith(GITHUB.ref_name,'feature/') && GITHUB.event_name == 'push'}}
    uses: eldeekhowong/shared-workflows/.github/workflows/eits-build-deploy.yaml@main
    secrets: inherit
    with:
      build-deploy: 'build'
      code-coverage-required: false

  Develop-PR:
    if: ${{ GITHUB.base_ref == 'develop' && GITHUB.event_name == 'pull_request'}}
    uses: eldeekhowong/shared-workflows/.github/workflows/eits-build-deploy.yaml@main
    secrets: inherit
    with:
      build-deploy: 'build'
      code-coverage-required: false #switch to true

  Develop-Merge:
    if: ${{ GITHUB.base_ref == 'develop' && GITHUB.event.pull_request.merged == true}}
    uses: eldeekhowong/shared-workflows/.github/workflows/eits-build-deploy.yaml@main
    secrets: inherit
    with:
      build-deploy: 'deploy'
      code-coverage-required: false #switch to true