name: EITS Mule Pipeline

on:
  workflow_call:

jobs:
  Feature-Branch-Commit:
    #if: ${{ GITHUB.event_name != 'pull_request' }}
    if: ${{ startsWith(GITHUB.ref_name,'feature/') && GITHUB.event_name == 'push'}}
    uses: eldeekhowong/shared-workflows/.github/workflows/build-test.yml@main
    secrets: inherit
    with:
      build-test: 'test-only'

  Develop-Merge:
    if: ${{ GITHUB.base_ref == 'develop' && GITHUB.event_name == 'pull_request'}}
    uses: eldeekhowong/shared-workflows/.github/workflows/build-test.yml@main
    secrets: inherit
    with:
      build-test: 'build'